### ISSUE TITLE
可视化程序

### ISSUE THREAD

**Issue by ghost233lism** [xuangu-fang/BayOTIDE#1]
作者您好！您的工作可以称得上是惊艳，我想进一步地进行测试，请问您是否方便公开可视化的代码呢？

**Comment by xuangu-fang** [comment]
你好，感谢关注和支持BayOTIDE! 可视化的代码在notebook里可以找到：[vis for simu](https://github.com/xuangu-fang/BayOTIDE/blob/master/notebook/fast_test_simu.ipynb)
